name: tests

on:
  push:
    branches:
    - self-hosted-runner

jobs:
  run-tests-self-runner:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Create conda env
      run: |
        which conda
        conda env list
        conda env remove -n self-hosted-runner
        conda create -n self-hosted-runner python=${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        echo "/Users/mingwang/miniconda3/envs/self-hosted-runner/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pwd
        conda list
        conda install grpcio
        pip install -e '.[atari, mujoco]'
        conda list
    - name: Install test dependencies
      run: |
        conda init bash
        pip install pytest
    - name: Run Pre-check
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: pytest -s tests/test_precheck.py & pytest -s tests/algo/test_pbt.py
    - name: Run tests
      run: |
        # run all tests
        pytest -s -k "not torch_tensor_share"
